# Day 10 — PostgreSQL + SQLAlchemy Setup
**Real Estate Fraud Detection**

Goal: Setup PostgreSQL database, create tables, test CRUD operations.

**Tables:**
- `prediction_logs` — every API prediction stored here
- `model_registry` — model versions + metrics

**Prerequisites:**
- PostgreSQL installed and running locally
- `.env` file created with `DATABASE_URL`

## 0. Set Project Root

In [1]:
import os
from pathlib import Path

project_root = Path.cwd()
while not (project_root / 'configs').exists():
    project_root = project_root.parent
os.chdir(project_root)
print(f'Working directory: {os.getcwd()}')

Working directory: c:\Users\mehal\Downloads\machinelearning\real_estate_fraud_detection

## 1. Install Dependencies

In [2]:
# Install required packages if not already installed
import subprocess, sys

packages = ['sqlalchemy', 'psycopg2-binary', 'python-dotenv']
for pkg in packages:
    try:
        __import__(pkg.replace('-', '_').split('==')[0])
        print(f'✅ {pkg} already installed')
    except ImportError:
        print(f'Installing {pkg}...')
        subprocess.run([sys.executable, '-m', 'pip', 'install', pkg, '-q'])

✅ sqlalchemy already installed
Installing psycopg2-binary...
Installing python-dotenv...

## 2. Imports & Config

In [3]:
import os, sys
sys.path.insert(0, os.path.abspath('.'))

import json
import pandas as pd
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

from src.ingestion import load_config
from src.database import (
    get_database_url, create_db_engine, create_session_factory,
    init_db, check_db_connection,
    PredictionLog, ModelRegistry,
    log_prediction, get_prediction_history,
    get_fraud_stats, register_model, get_active_model,
)

# Load .env file — DATABASE_URL etc
load_dotenv()

cfg = load_config('configs/config.yaml')
print(f'Config: {cfg["project"]["name"]}')
print(f'Database URL: {get_database_url().split("@")[-1]}')  # show host only

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\ProgramData\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\ProgramData\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\ProgramData\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "c:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "c:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "c:\ProgramData\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\mehal\AppData\Local\Temp\ipykernel_1316\1496291146.py", line 5, in <module>
    import pandas as pd
  File "C:\Users\mehal\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 38, in <module>
    from pandas.compat import (
  File "C:\Users\mehal\AppData\Roaming\Python\Python312\site-packages\pandas\compat\__init__.py", line 29, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\mehal\AppData\Roaming\Python\Python312\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "c:\ProgramData\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\ProgramData\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\ProgramData\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\ProgramData\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "c:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "c:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "c:\ProgramData\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\mehal\AppData\Local\Temp\ipykernel_1316\1496291146.py", line 5, in <module>
    import pandas as pd
  File "C:\Users\mehal\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 61, in <module>
    from pandas.core.api import (
  File "C:\Users\mehal\AppData\Roaming\Python\Python312\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\mehal\AppData\Roaming\Python\Python312\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "c:\ProgramData\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

2026-05-18 16:56:58,123 - src.ingestion - INFO - Config loaded from configs\config.yaml — project: real_estate_fraud_detection v1.1.0

Config: real_estate_fraud_detection
Database URL: localhost:5432/fraud_db

## 3. PostgreSQL Setup Check

> **Agar PostgreSQL install nahi hai:**
> ```
> Windows: https://www.postgresql.org/download/windows/
> Download karo, install karo, default port 5432 rakho
> ```
>
> **Database + User banao (pgAdmin ya psql se):**
> ```sql
> CREATE USER fraud_user WITH PASSWORD 'fraud_pass';
> CREATE DATABASE fraud_db OWNER fraud_user;
> GRANT ALL PRIVILEGES ON DATABASE fraud_db TO fraud_user;
> ```
>
> **`.env` file project root mein banao:**
> ```
> DATABASE_URL=postgresql://fraud_user:fraud_pass@localhost:5432/fraud_db
> API_KEY=dev-secret-key-change-in-production
> ```

In [4]:
# Create engine and test connection
try:
    engine = create_db_engine(echo=False)
    connected = check_db_connection(engine)
    if connected:
        print('✅ PostgreSQL connection successful!')
        print(f'   Host: {get_database_url().split("@")[-1]}')
    else:
        print('❌ Connection failed — check PostgreSQL is running and .env is correct')
except Exception as e:
    print(f'❌ Error: {e}')
    print('\nTroubleshooting:')
    print('  1. PostgreSQL service running? (Windows: Services → PostgreSQL)')
    print('  2. .env file mein DATABASE_URL correct hai?')
    print('  3. fraud_db database exist karta hai?')

2026-05-18 16:57:01,371 - src.database - INFO - Database engine created — localhost:5432/fraud_db

✅ PostgreSQL connection successful!
   Host: localhost:5432/fraud_db

## 4. Create Tables

In [5]:
# Create all tables
init_db(engine)
print('✅ Tables created/verified:')
print('   - prediction_logs')
print('   - model_registry')

# Verify tables exist
from sqlalchemy import inspect
inspector = inspect(engine)
tables = inspector.get_table_names()
print(f'\nTables in database: {tables}')

# Show column info
for table in tables:
    cols = [c['name'] for c in inspector.get_columns(table)]
    print(f'\n{table} columns ({len(cols)}):')
    print(f'  {cols}')

2026-05-18 16:57:01,650 - src.database - INFO - Database tables created/verified: prediction_logs, model_registry

✅ Tables created/verified:
   - prediction_logs
   - model_registry

Tables in database: ['prediction_logs', 'model_registry']

prediction_logs columns (18):
  ['id', 'created_at', 'price', 'bed', 'bath', 'house_size', 'acre_lot', 'city', 'state', 'zip_code', 'status', 'fraud_score', 'is_suspicious', 'risk_tier', 'shap_top3', 'model_version', 'latency_ms', 'api_key_hash']

model_registry columns (12):
  ['id', 'registered_at', 'model_name', 'version', 'stage', 'pr_auc', 'recall_at_95p', 'threshold', 'model_path', 'mlflow_run_id', 'is_active', 'notes']

## 5. Test — Log Sample Predictions

In [6]:
SessionLocal = create_session_factory(engine)

# Sample predictions to test CRUD
sample_predictions = [
    {
        'price': 85000.0, 'bed': 3.0, 'bath': 2.0,
        'house_size': 1500.0, 'acre_lot': 0.15,
        'city': 'Austin', 'state': 'TX',
        'zip_code': '78701', 'status': 'for_sale',
        'fraud_score': 0.82,
        'is_suspicious': True,
        'risk_tier': 'HIGH',
        'shap_top3': json.dumps([
            {'feature': 'price_vs_city_median', 'impact': 1.21, 'value': 0.31},
            {'feature': 'price_per_sqft',       'impact': 0.84, 'value': 56.67},
            {'feature': 'city_fraud_rate',       'impact': 0.52, 'value': 0.08},
        ]),
        'model_version': cfg['project']['version'],
        'latency_ms': 42.3,
    },
    {
        'price': 450000.0, 'bed': 4.0, 'bath': 3.0,
        'house_size': 2200.0, 'acre_lot': 0.25,
        'city': 'Denver', 'state': 'CO',
        'zip_code': '80201', 'status': 'for_sale',
        'fraud_score': 0.12,
        'is_suspicious': False,
        'risk_tier': 'LOW',
        'shap_top3': json.dumps([
            {'feature': 'price_vs_city_median', 'impact': -0.45, 'value': 0.98},
            {'feature': 'price_per_sqft',       'impact': -0.32, 'value': 204.5},
            {'feature': 'city_fraud_rate',       'impact': -0.18, 'value': 0.04},
        ]),
        'model_version': cfg['project']['version'],
        'latency_ms': 38.7,
    },
    {
        'price': 180000.0, 'bed': 3.0, 'bath': 2.0,
        'house_size': 1800.0, 'acre_lot': 0.20,
        'city': 'Miami', 'state': 'FL',
        'zip_code': '33101', 'status': 'for_sale',
        'fraud_score': 0.55,
        'is_suspicious': False,
        'risk_tier': 'MEDIUM',
        'shap_top3': json.dumps([
            {'feature': 'price_vs_city_median', 'impact': 0.32, 'value': 0.71},
            {'feature': 'city_fraud_rate',       'impact': 0.28, 'value': 0.09},
            {'feature': 'price_per_sqft',        'impact': 0.15, 'value': 100.0},
        ]),
        'model_version': cfg['project']['version'],
        'latency_ms': 45.1,
    },
]

with SessionLocal() as db:
    logged = []
    for pred in sample_predictions:
        log = log_prediction(db, pred)
        logged.append(log)
        print(f'✅ Logged: id={log.id} | city={log.city} | score={log.fraud_score:.2f} | tier={log.risk_tier}')

print(f'\n{len(logged)} predictions logged successfully')

✅ Logged: id=1 | city=Austin | score=0.82 | tier=HIGH
✅ Logged: id=2 | city=Denver | score=0.12 | tier=LOW
✅ Logged: id=3 | city=Miami | score=0.55 | tier=MEDIUM

3 predictions logged successfully

## 6. Test — Query History

In [7]:
with SessionLocal() as db:
    # All predictions
    all_preds = get_prediction_history(db, limit=10)
    print(f'Total predictions in DB: {len(all_preds)}')

    # Filter by risk tier
    high_risk = get_prediction_history(db, risk_tier='HIGH')
    print(f'HIGH risk predictions  : {len(high_risk)}')

    # Filter by min score
    suspicious = get_prediction_history(db, min_score=0.70)
    print(f'Score >= 0.70          : {len(suspicious)}')

# Show as DataFrame
rows = []
with SessionLocal() as db:
    preds = get_prediction_history(db, limit=10)
    for p in preds:
        rows.append({
            'id': p.id,
            'city': p.city,
            'state': p.state,
            'price': p.price,
            'fraud_score': p.fraud_score,
            'risk_tier': p.risk_tier,
            'latency_ms': p.latency_ms,
            'created_at': p.created_at,
        })

df = pd.DataFrame(rows)
print('\nPrediction history:')
df

Total predictions in DB: 3
HIGH risk predictions  : 1
Score >= 0.70          : 1

Prediction history:

,id,city,state,price,fraud_score,risk_tier,latency_ms,created_at
0,3,Miami,FL,180000.0,0.55,MEDIUM,45.1,2026-05-18 11:27:01.815731
1,2,Denver,CO,450000.0,0.12,LOW,38.7,2026-05-18 11:27:01.807790
2,1,Austin,TX,85000.0,0.82,HIGH,42.3,2026-05-18 11:27:01.785335

## 7. Test — Fraud Stats (Analytics Dashboard)

In [8]:
with SessionLocal() as db:
    stats = get_fraud_stats(db)

print('=== FRAUD STATISTICS ===')
print(f'Total predictions : {stats["total_predictions"]}')
print(f'Suspicious count  : {stats["suspicious_count"]}')
print(f'Fraud rate        : {stats["fraud_rate"]*100:.1f}%')
print(f'Avg fraud score   : {stats["avg_fraud_score"]:.4f}')
print(f'\nTier breakdown    : {stats["tier_counts"]}')
print(f'Top fraud cities  : {stats["top_fraud_cities"]}')

=== FRAUD STATISTICS ===
Total predictions : 3
Suspicious count  : 1
Fraud rate        : 33.3%
Avg fraud score   : 0.4967

Tier breakdown    : {'MEDIUM': 1, 'HIGH': 1, 'LOW': 1}
Top fraud cities  : [{'city': 'Austin', 'count': 1}]

## 8. Test — Model Registry

In [9]:
# Register current model
with SessionLocal() as db:
    model = register_model(
        db=db,
        model_name='fraud_detector',
        version=cfg['project']['version'],
        stage='Production',
        pr_auc=0.7694,
        recall_at_95p=0.1105,
        threshold=cfg['api']['fraud_threshold_suspicious'],
        model_path=cfg['paths']['calibrated_model'],
        notes='Stacked + Platt calibrated — Day 8',
    )
    print(f'✅ Model registered: {model}')

# Verify active model
with SessionLocal() as db:
    active = get_active_model(db)
    print(f'\nActive model: {active.model_name} v{active.version}')
    print(f'  Stage     : {active.stage}')
    print(f'  PR-AUC    : {active.pr_auc}')
    print(f'  Threshold : {active.threshold}')

2026-05-18 16:57:01,998 - src.database - INFO - Model registered — fraud_detector v1.1.0 (Production)

✅ Model registered: <ModelRegistry fraud_detector v1.1.0 stage=Production pr_auc=0.7694>

Active model: fraud_detector v1.1.0
  Stage     : Production
  PR-AUC    : 0.7694
  Threshold : 0.7

## 9. Raw SQL Verify

In [10]:
# Verify with raw SQL — confirms data actually in PostgreSQL
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text('SELECT * FROM prediction_logs LIMIT 5'))
    rows = result.fetchall()
    cols = result.keys()

raw_df = pd.DataFrame(rows, columns=cols)
print(f'Raw SQL — prediction_logs ({len(raw_df)} rows):')
raw_df[['id', 'city', 'state', 'fraud_score', 'risk_tier', 'latency_ms']]

Raw SQL — prediction_logs (3 rows):

   id    city state  fraud_score risk_tier  latency_ms
0   1  Austin    TX         0.82      HIGH        42.3
1   2  Denver    CO         0.12       LOW        38.7
2   3   Miami    FL         0.55    MEDIUM        45.1

## 10. Connection Pooling Info

In [11]:
pool = engine.pool
print('Connection pool status:')
print(f'  Pool size    : {pool.size()}')
print(f'  Checked out  : {pool.checkedout()}')
print(f'  Overflow     : {pool.overflow()}')
print(f'  Checked in   : {pool.checkedin()}')
print('\n✅ Connection pooling configured — production ready')

Connection pool status:
  Pool size    : 5
  Checked out  : 0
  Overflow     : -4
  Checked in   : 1

✅ Connection pooling configured — production ready

## 11. Day 10 Exit Criteria

In [12]:
print('=== DAY 10 EXIT CRITERIA ===')

with SessionLocal() as db:
    total_preds  = len(get_prediction_history(db, limit=1000))
    active_model = get_active_model(db)
    stats        = get_fraud_stats(db)

checks = [
    ('PostgreSQL connected',
     check_db_connection(engine)),
    ('prediction_logs table exists',
     'prediction_logs' in inspect(engine).get_table_names()),
    ('model_registry table exists',
     'model_registry' in inspect(engine).get_table_names()),
    ('Sample predictions logged',
     total_preds >= 3),
    ('Model registered in registry',
     active_model is not None),
    ('CRUD operations work',
     stats['total_predictions'] >= 3),
    ('Connection pooling configured',
     engine.pool.size() > 0),
    ('.env file exists',
     Path('.env').exists()),
]

all_pass = True
for label, result in checks:
    icon = '☑' if result else '☒'
    if not result: all_pass = False
    print(f'  {icon} {label}')

print(f'\n{"✅ All passed" if all_pass else "⚠️ Some failed"}')
print(f'\n→ Ready for Day 11 — FastAPI Inference Endpoint')

=== DAY 10 EXIT CRITERIA ===
  ☑ PostgreSQL connected
  ☑ prediction_logs table exists
  ☑ model_registry table exists
  ☑ Sample predictions logged
  ☑ Model registered in registry
  ☑ CRUD operations work
  ☑ Connection pooling configured
  ☑ .env file exists

✅ All passed

→ Ready for Day 11 — FastAPI Inference Endpoint